language: ruby
rvm:
- 2.4.1
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rspec
services:
- postgresql
notifications:
  email: false
env:
  global:
  - secure: B3SyadF2fV26KB7I8SZaYkhhtw19A5p20HIrGfEN06Rwhe0tGuLIWUWVLq68LwGdQsGQPI+PI1DeoZjbW4Yx5I/GeVouHKd+TdHA08P+aV/1329aEorAvmoYIEPhFap8cbXUpYV7S7iNJmx6c3JdOj1HvAS2/iNx0g83wihBQeJbfSorAY6gFT18J8dcIC5zmMm57I9IFOvELUO6/epjZg05Vk0oNxf6uZAHYPBEIQ4Ysw60992Z8xwnQMeWtMBLQXl8942KlFdQUf5xYUQJRRZWIRNi2VTNDiEoWbErfO+FJXX9DHc9Us7HE6AYRLzMq1iogzGiil/twYxU/s4NGQFitefzBOvyaQJYZcska0f1dcFpA9EjIzt6zKI/5OopVZcch8p8FPnDeUcL7Ntek5ummZcINFXrA0g65RpLbmGcdB8rl/x7eQqwrCiHLceEfBScpZ+P1ijE4L4FZeQ1ocnNb0oU+CLfUFqHzEXgVSkpH1T+e+7a4zRE2kdzBna/8y9L8N6jNDNLpTbbvVZVTBpUA3xxzcBchyiwQO0OKuMmf79iFNz4XobiuzqK3sikOHuxJNmGUS+oL+n1FcTeu1XQVwr5mC/pyLuEVzKhDd3JKjHl6b3ZhtsXppjiFwW3A7HbVxs3/jE2CclxP3kY3EpxLkzNzd4+lc3Y8pdu3CM=
